### ISSUE TITLE
Replace pip.main() in installer

### ISSUE THREAD

**Issue by paigevegna** [robotpy/robotpy-installer#20] opened 2018-11-27 22:33 UTC
The installer script uses the older version of the `pip` package. Specifically, the code uses the `pip.main()` function, which has been removed since pip version 10.

A quick workaround would be [the callable-pip package](https://pypi.org/project/callable-pip/), a wrapper around pip that allows you to use the `pip.main()` syntax that's currently there. The long-term solution would be to either using `subprocess` to call pip or using import statements.

**Comment by auscompgeek** [comment] 2018-11-28 00:36
Huh, I could've sworn we fixed this.

**Comment by virtuald** [comment] 2018-11-28 00:38
Ah yes, duplicate of #15 . @paigevegna if you upgrade your version of the installer it should work for you!

**Closed by virtuald** 2018-11-28 00:38 UTC
